# Generated by Django 3.1 on 2021-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210513_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'QuestionCategory'},
        ),
        migrations.AddField(
            model_name='question',
            name='marks_per_question',
            field=models.IntegerField(default=5),
        ),
    ]
