# Generated by Django 3.1 on 2021-05-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizstatus',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
