# Generated by Django 3.1 on 2021-05-13 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizstatus_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective_answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.choice')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question')),
                ('quiz_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizstatus')),
            ],
        ),
    ]
