# Generated by Django 3.1 on 2021-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_questionattempted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionattempted',
            old_name='answer',
            new_name='answer_answered_by_user',
        ),
        migrations.AddField(
            model_name='questionattempted',
            name='marks',
            field=models.IntegerField(default=-1),
        ),
    ]
